// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByk4iVBo3M4F50SwM3PtE10z__IO0OVlw',
    appId: '1:784554507077:web:95598ad506fb02091a1c2c',
    messagingSenderId: '784554507077',
    projectId: 'urbansafe-app01',
    authDomain: 'urbansafe-app01.firebaseapp.com',
    storageBucket: 'urbansafe-app01.firebasestorage.app',
    measurementId: 'G-J1RVFM513W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgHYCi-saYkBkVS_PMt_YaPXdn0CO6BGo',
    appId: '1:784554507077:android:f8abeaadee245c011a1c2c',
    messagingSenderId: '784554507077',
    projectId: 'urbansafe-app01',
    storageBucket: 'urbansafe-app01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3gxTsBrNZFg1GePOLMPsMQeGB1szMkUk',
    appId: '1:784554507077:ios:7ae0d83ecb8d185d1a1c2c',
    messagingSenderId: '784554507077',
    projectId: 'urbansafe-app01',
    storageBucket: 'urbansafe-app01.firebasestorage.app',
    iosBundleId: 'com.example.urbansafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3gxTsBrNZFg1GePOLMPsMQeGB1szMkUk',
    appId: '1:784554507077:ios:7ae0d83ecb8d185d1a1c2c',
    messagingSenderId: '784554507077',
    projectId: 'urbansafe-app01',
    storageBucket: 'urbansafe-app01.firebasestorage.app',
    iosBundleId: 'com.example.urbansafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByk4iVBo3M4F50SwM3PtE10z__IO0OVlw',
    appId: '1:784554507077:web:6fd7626614090a921a1c2c',
    messagingSenderId: '784554507077',
    projectId: 'urbansafe-app01',
    authDomain: 'urbansafe-app01.firebaseapp.com',
    storageBucket: 'urbansafe-app01.firebasestorage.app',
    measurementId: 'G-7K3F0TVCET',
  );

}