#import "@local/utp-doc:1.0.0": pc

= Análisis de la situación

== Antecedentes

// busqueda scopus: TITLE-ABS-KEY ( ( "machine learning" OR "artificial intelligence" ) AND ( "risk prediction" OR "crime prediction" ) AND ( "public safety" OR "citizen security" ) ) AND PUBYEAR > 2020 AND PUBYEAR < 2026 AND ( LIMIT-TO ( OA , "all" ) ) AND ( LIMIT-TO ( DOCTYPE , "ar" ) OR LIMIT-TO ( DOCTYPE , "cp" ) )
// dos antecedentes internacionales
Diversos estudios y proyectos han abordado la necesidad de desarrollar un sistema que ayude a detectar la probabilidad de riesgo en una ciudad utilizando machine learning, demostrando su efectividad en entornos urbanos. 

El estudio de #pc[@s2024] introduce el uso del aprendizaje automático para superar las limitaciones de los métodos tradicionales de análisis delictivo. Así, el objetivo fue predecir las tendencias de criminalidad en la India de 2017 a 2020, utilizando para ello un conjunto de datos que abarca desde 2001 hasta 2016. El procedimiento consistió en entrenar algoritmos como Regresión Lineal y Random Forest con datos históricos para identificar patrones y generar proyecciones. Como resultado, se obtuvieron predicciones con una alta tasa de precisión, alcanzando un 94% para intentos de asesinato y un 95% para casos de violación y robo. En conclusión, la investigación confirma que el aprendizaje automático es una herramienta eficaz para predecir delitos, destacando el modelo K-nearest neighbour por su precisión. Sin embargo, el estudio reconoce limitaciones, como la dificultad de predecir crímenes violentos de naturaleza aleatoria y los desafíos que presenta el modelado en áreas con bajos índices de criminalidad. 

El estudio de #pc[@butt2021] aborda el desafío de la seguridad en las ciudades inteligentes, donde el aumento de la población requiere métodos más eficientes para garantizar la protección de los ciudadanos. Por ello, el objetivo principal fue desarrollar un nuevo enfoque para identificar y predecir zonas de alta criminalidad (hot-spots), permitiendo a las autoridades visualizar mejor las amenazas y planificar acciones preventivas. Para lograrlo, se utilizó un modelo que primero aplica el algoritmo HDBSCAN para detectar los puntos calientes en un conjunto de datos de 10 años de la ciudad de Nueva York y, posteriormente, emplea el modelo SARIMA para predecir el número futuro de incidentes en cada una de esas zonas. Como resultado, el enfoque propuesto superó a otros métodos de última generación, logrando un Error Absoluto Medio (MAE) de 11.47, lo que demuestra una mayor precisión. En conclusión, el estudio confirma que el sistema es un enfoque práctico y rentable que detecta y predice la delincuencia con éxito, validando la superioridad del modelo SARIMA. Finalmente, la investigación propone como futuras mejoras el uso del aprendizaje por transferencia (transfer learning) y conjuntos de clústeres para optimizar aún más el rendimiento del modelo. 

Respecto a estudios de índole nacional se consideraron los siguientes: 

Según la investigación de #pc[@ochante-huamaccto2022], el cual aborda el problema global de la inseguridad ciudadana, proponiendo la tecnología como una solución viable. Por ello, el objetivo fue desarrollar una aplicación móvil basada en el internet de las cosas (IoT) para mapear delitos y medir su impacto en la mejora de la seguridad. El procedimiento consistió en crear la aplicación utilizando la metodología Scrum, la cual fue probada por 96 ciudadanos en un distrito de Ayacucho, Perú, para reportar incidentes en tiempo real. Como resultado, la implementación de la aplicación logró un aumento del 102.7% en los reportes de zonas peligrosas, un 25.34% en los reportes por tipo de delito y una mejora del 23.5% en el tiempo de respuesta de las autoridades. En conclusión, se determinó que la aplicación móvil tiene una influencia positiva y significativa en el combate al crimen y se recomienda continuar su desarrollo para satisfacer las nuevas necesidades de los usuarios. Finalmente, una limitación del estudio es su enfoque en una población y un distrito geográfico muy específico de Perú, lo que podría afectar la generalización de los resultados. 

En tal sentido, #pc[@mansilla2023] en su estudio aborda la alta percepción de inseguridad en el distrito de Los Olivos, en Lima, mediante una solución tecnológica. Así, el objetivo fue desarrollar una aplicación basada en machine learning que envía alertas en tiempo real a los usuarios, indicando la probabilidad de que un área sea insegura. Para lograrlo, se utilizó el algoritmo Naive Bayes, entrenado con un conjunto de datos delictivos, y se validó el sistema con una muestra de 108 usuarios a través de un cuestionario. Como resultado, la solución obtuvo una aceptación del 93.5% entre los usuarios, quienes consideraron que ayuda a prevenir el crimen, y el algoritmo Naive Bayes demostró ser el más preciso y rápido en comparación con otros. En conclusión, se establece que la tecnología de aprendizaje automático es una herramienta innovadora y eficaz para la seguridad ciudadana, con potencial para ser replicada en otros distritos. Finalmente, una limitación del estudio es su enfoque geográfico específico en un solo distrito, además de la dependencia de los datos disponibles en la plataforma "Datacrime" para el entrenamiento del modelo.

#pagebreak()
== Problemas generales relacionados a otras fuentes
La región del Callao enfrenta serias problemáticas en materia de seguridad ciudadana, producto del incremento de hechos delictivos y la limitada eficacia de los métodos tradicionales de prevención. Esta situación genera desconfianza en la población y limita la capacidad de respuesta de las autoridades. Ante ello, se plantea la necesidad de soluciones tecnológicas innovadoras, como una aplicación móvil basada en machine learning, que permita optimizar la predicción de riesgos y fortalecer la seguridad en la región. 

Según #pc[@amadoasenjo2024] en su investigación sobre la seguridad ciudadana en la región del Callao, se identificaron diversos problemas generales que afectan directamente la percepción y efectividad de la seguridad en la zona. Entre ellos destaca una alta percepción de inseguridad por parte de la población, que alcanzó hasta el 89,6%, lo cual refleja una desconfianza significativa hacia las autoridades y el sistema de protección ciudadana. Asimismo, se evidenció una baja participación ciudadana en actividades relacionadas con la seguridad, con solo un 36,58% de la población colaborando en iniciativas comunitarias o coordinaciones con las autoridades locales. Finalmente, se determinó que existe una relación inversa entre la participación ciudadana y los niveles de inseguridad, ya que, a mayor involucramiento de la comunidad, se observan mejoras sustanciales en la prevención y reducción de actos delictivos. 

Tal como expone #pc[@monteagudotalaverano2019] en su estudio se identifican diversos problemas generales que afectan la seguridad en la región Callao. Entre ellos destaca el incremento de la delincuencia común y organizada, así como la percepción de inseguridad que experimenta la población debido a la limitada eficacia de los sistemas de prevención. El autor señala además la deficiente articulación entre las instituciones responsables, la escasa infraestructura tecnológica y la ausencia de un planeamiento estratégico que permita optimizar los recursos disponibles para la seguridad. También se evidencian delitos frecuentes como robos, asaltos, homicidios y violencia familiar, los cuales impactan directamente en la convivencia social. Estos hallazgos reflejan la necesidad de implementar estrategias innovadoras y coordinadas que fortalezcan la capacidad de respuesta de las autoridades y contribuyan a disminuir los niveles de inseguridad en la provincia del Callao. 

Por su parte #pc[@sanchezblanco2018] en su estudio aborda el análisis de los registros policiales de la comisaría de Carmen de La Legua Reynoso evidencia una situación alarmante en materia de seguridad ciudadana. Se observa un elevado índice de denuncias por delitos, representando un 62 % del total de casos, mientras que el 64 % de las personas detenidas están directamente vinculadas a actividades delictivas. Asimismo, se identificó que el 79 % de los reportes corresponden a faltas menores, lo que denota una problemática constante de alteraciones del orden público y conflictos sociales que requieren atención preventiva. Otro aspecto crítico es la presencia de homicidios clasificados como de alta incidencia (50 %), sumado a un 67 % de desarticulación de bandas delictivas, lo que refleja la existencia de organizaciones criminales con un impacto considerable en la percepción de inseguridad de la población. Del mismo modo, los robos vehiculares constituyen otro problema recurrente, alcanzando un 67 % de las denuncias, con un 57 % de vehículos recuperados, lo que evidencia tanto la magnitud del problema como las limitaciones en la respuesta efectiva. Finalmente, las denuncias por violencia familiar y otros tipos de violencia interpersonal también resaltan como problemáticas que afectan la convivencia social y la sensación de seguridad en la comunidad, dejando en claro la necesidad de estrategias integrales que combinen prevención, tecnología y coordinación interinstitucional para mejorar los índices de seguridad en la región.

#pagebreak()
== Marco teórico

En el desarrollo de un modelo para la predicción de riesgo y una aplicación móvil, es importante poder comprender las teorías y conceptos que fundamentan este desarrollo. A continuación, se presenta un análisis teórico que sustenta el proyecto, abordando aspectos esenciales como machine learning, aplicación móvil, seguridad ciudadana, violencia física, violencia psicológica, conducción en estado de ebriedad y hurto. 

#pc[@morenoponcej.a.2016] define la seguridad ciudadana como un problema que tiene muchas causas y que debe entenderse considerando varios aspectos al mismo tiempo, como lo social, lo económico, lo político y lo territorial. Esto es especialmente importante cuando estos factores se vuelven constantes y afectan de forma directa a ciertos barrios o zonas de la ciudad. De igual manera, #pc[@figueroagutarra2024] la considera un derecho humano independiente, que no solo debe ser garantizado por el Estado, sino también por la sociedad en general. Para lograrlo, es necesario que las personas participen activamente en su protección, ayudando a crear políticas públicas que respeten los derechos humanos, fortalezcan la democracia y promuevan una convivencia más segura. 

#pc[@nazar2018] definen la violencia física como una problemática estructural que se manifiesta principalmente en el hogar, y que afecta de manera diferenciada a niños, niñas y adolescentes. Según los autores, esta forma de violencia no debe entenderse únicamente como una práctica disciplinaria, sino como una expresión abusiva del poder que ejercen los adultos sobre los menores, especialmente en contextos donde existe una tolerancia social y cultural hacia el uso de la fuerza física. La violencia física se presenta como un fenómeno acumulativo, que se intensifica en hogares con condiciones de vulnerabilidad, como la pobreza, la ausencia de uno o ambos padres, o la presencia de figuras sustitutas como padrastros o madrastras. 

Como afirman #pc[@ruizcastro2024], la violencia psicológica es una forma de agresión que busca controlar o dañar emocionalmente a una persona mediante conductas como amenazas, manipulación, humillación, aislamiento o chantaje. Este tipo de violencia no deja marcas visibles, pero puede causar un profundo daño emocional, afectando la autoestima, el equilibrio mental y la estabilidad personal de la víctima. En el contexto familiar, se presenta como una práctica persistente que se normaliza por factores culturales, sociales y económicos, lo que hace que muchas víctimas no reconozcan el maltrato o incluso lo justifiquen. 

#pc[@teeters2018] definen a la conducción en estado de ebriedad como una conducta de alto riesgo que implica manejar un vehículo después de haber consumido alcohol en cantidades que afectan la capacidad de reacción, el juicio y el control físico. Además, señalan que este comportamiento representa una de las principales causas de muerte relacionada con el consumo de alcohol entre estudiantes universitarios, y que a pesar de las campañas de prevención, sigue siendo una práctica común en este grupo.

En cuanto al hurto, #pc[@olivercalderon2011] lo define como un delito que consiste en apropiarse de una cosa mueble ajena sin la voluntad de su dueño y con ánimo de lucro. Esta conducta implica que el autor se apodera de un objeto físico que pertenece a otra persona, con la intención de obtener algún beneficio. Además, aclara que el hurto no convierte al autor en dueño legítimo del objeto, sino que simplemente lo priva de su posesión. El hurto se diferencia del robo en que no se emplea violencia, intimidación ni fuerza en las cosas. 

Con el propósito de definir la tecnología que se va a utilizar, #pc[@mitchell2013] define al machine learning como un proceso mediante el cual un programa de computadora mejora su capacidad para realizar una tarea específica a medida que acumula experiencia. Esta mejora se evalúa a través de una medida de rendimiento que permite observar si el sistema está aprendiendo de manera efectiva. En otras palabras, el aprendizaje ocurre cuando el desempeño del programa en una actividad concreta se vuelve más preciso o eficiente gracias a la información que ha recibido previamente. Asimismo, #pc[@r2021] considera que el machine learning es una disciplina que permite a las computadoras aprender a realizar tareas sin necesidad de ser programadas paso a paso por humanos. Según los autores, este proceso se basa en alimentar al sistema con datos de buena calidad, a partir de los cuales se construyen modelos que permiten a las máquinas tomar decisiones o hacer predicciones. En este sentido, el machine learning se convierte en una herramienta útil para resolver problemas complejos en áreas como la medicina, la visión por computadora, el análisis de datos y la clasificación de información, donde sería difícil o incluso imposible diseñar manualmente una solución precisa. 

Para poder facilitar la interacción del modelo con el usuario, es importante definir las aplicaciones móviles. #pc[@acostaespinoza2022] lo define como herramientas digitales diseñadas para funcionar en dispositivos portátiles, como teléfonos inteligentes, que permiten a los usuarios acceder de forma rápida y eficiente a información, servicios o funciones específicas. Según los autores, estas aplicaciones se han convertido en el principal canal de comunicación entre las instituciones y la sociedad, gracias a su versatilidad, disponibilidad permanente y facilidad de uso.

#pagebreak()
